### ISSUE TITLE
pyglet.image.load_animation() fails when decoder is specified

### ISSUE THREAD

**Issue by mcgoober** [adamlwgriffiths/Pyglet#2]
**Symptom**:
If I load an animation image by using a custom decoder I get NotImplementedError.
e.g.
```
import io
from pyglet.image import *
from pyglet.image.codecs import *

class MyFileDecoder(ImageDecoder):
    def __init__(self, width, height, palette):
        pass
    def decode_animation(self, file, filename):
        return Animation([ImageData(0, 0, 'RGBA', [], 0)])

palette = []
myFileData = io.BytesIO(bytes([1, 2]))

myFileAnimation = pyglet.image.load_animation('myFile', 
    file=myFileData, decoder=MyFileDecoder(640, 480, palette))
```

**Expected Result**:
The animation should be loaded correctly without throwing any errors.

**Workaround**:
In the case when a decoder is specified to load_animation(), a call to decoder.decode() is made, however it should be decoder.decode_animation().
See... [https://github.com/adamlwgriffiths/Pyglet/blob/7ced33347a70bbaa02bab7ad28ad3c976bd9b216/pyglet/image/__init__.py#L2496](https://github.com/adamlwgriffiths/Pyglet/blob/7ced33347a70bbaa02bab7ad28ad3c976bd9b216/pyglet/image/__init__.py#L2496)
In the snippet, when a decoder isn't specified it goes through registered decoders looking for one that handles the file type. Once one is found decoder.decode_animation() is called.
By changing line 2496 above as follows, the code works as expected.
```
        return decoder.decode_animation(file, filename)
```

**Comment by adamlwgriffiths** [comment]
Not sure why you're putting this here. This is a 7 year old fork of pyglet.

**Comment by mcgoober** [comment]
Ah, sorry. Google searched, and yours is the root of 8 other forks. Assumed it was the master. Probably should have read the docs.
