### ISSUE TITLE
Menu bar

### ISSUE THREAD

**Issue by EdwardWatine** [adamlwgriffiths/Pyglet#3]
On tkinter it is very straightforward to create a menu bar for the window, for example like the one at the top of IDLE. 
![image](https://user-images.githubusercontent.com/32309654/57988447-75149400-7a86-11e9-8e4b-e69d5f3c983f.png) 
Is this at all supported by pyglet or even OpenGL?

**Comment by adamlwgriffiths** [comment]
Description: Fork of Pyglet to provide OpenGL Core functionality on Mac OS-X. Please use the official repository unless you require these changes.
